#-------------------------------
# General Site Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tech.jtcarrasco.com" # the base hostname & protocol for your site

# port for tailscale
host: 0.0.0.0
port: 4002


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-sitemap


#-------------------------------
# Collections
collections:
  pages:
    output: true
    permalink: /:name

# Pages Path
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

sass:
  style: compressed
